#!/bin/bash

KEXT="/Library/Extensions/softu2f.kext"
LAUNCH_AGENT_PLIST="$HOME/Library/LaunchAgents/com.github.SoftU2F.plist"

kextunload $KEXT || true
sudo -u "${USER}" launchctl unload $LAUNCH_AGENT_PLIST || true
